// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Timestamp.Infrastructure;

#nullable disable

namespace Timestamp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250812152059_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Timestamp.Domain.Models.Results", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageExecutionTime")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("AverageValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("DeltaTime")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MedianValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Timestamp.Domain.Models.Values", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExecutionTime")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ResultsId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ResultsId");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Timestamp.Domain.Models.Values", b =>
                {
                    b.HasOne("Timestamp.Domain.Models.Results", "Results")
                        .WithMany("ValuesList")
                        .HasForeignKey("ResultsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Timestamp.Domain.Models.Results", b =>
                {
                    b.Navigation("ValuesList");
                });
#pragma warning restore 612, 618
        }
    }
}
